version: "3.9"

services:
  pipeline:
    build:
      context: ./pipeline
    container_name: pipeline
    restart: unless-stopped
    ports:
      - "8001:8001"
    env_file:
      - ./.env
    volumes:
      - ./shared:/shared


  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "8002:80"
    depends_on:
      - pipeline


  preprocessing:
    build:
      context: ./preprocessing
    container_name: preprocessing
    restart: unless-stopped
    ports:
      - "8003:8003"
    env_file:
      - ./.env
    volumes:
      - ./shared:/shared
    depends_on:
      - pipeline
